sudo: required
language: python
services:
  - docker
python:
    - "3.5"
before_install:
  - sudo apt-get update
script: 
  - python --version
after_success:
  - docker login -u="chihchinag" -p="690927JOHNchen"
  - docker build -t chihchinag/travisci:1 . 
  - docker push chihchinag/travisci:1;
